# 들어가기 {.unnumbered}

## 1. 파이썬 개요

- @sec-language
- @sec-programming-language
- @sec-python-intro
- @sec-python-installation
- @sec-dev-environment
- @sec-1st-program
- @sec-10-ref

## 2. 문법

- @sec-storage
- @sec-variable
- @sec-datatype
- @sec-operator
- @sec-comment
- @sec-20-ref

## 3. 자료형

- @sec-list
- @sec-tuple
- @sec-dictionary
- @sec-set
- @sec-30-ref

## 4. 제어문

- @sec-condition-statement (@sec-if, ...)
- @sec-loop (@sec-for, @sec-while, ...)
- @sec-other-control-statement
- @sec-40-ref

## 5. 함수와 모듈

- @sec-function
- @sec-module
- @sec-package
- @sec-50-ref

## 6. 파일 입출력

- @sec-file-open
- @sec-file-write
- @sec-file-read
- @sec-60-ref

## 7. 예외 처리와 디버깅깅

- @sec-exception
- @sec-debugging
- @sec-70-ref

## 8. 클래스

- @sec-class-intro
- @sec-class-definition
- @sec-class-init-del
- @sec-class-variable
- @sec-class-method
- @sec-class-access
- @sec-class-inheritance
- @sec-class-polymorphism
- @sec-class-operator-overloading
- @sec-class-example

## 9. 주요 패키지 

- @sec-package
- @sec-package-search

## 참고자료 {.unlisted}

1. 코드 시각화 - [https://pythontutor.com/visualize.html#mode=edit](https://pythontutor.com/visualize.html#mode=edit){target="_blank"}
